name: 'bach-build'

description: 'Build a modular Java project with Bach'

branding:
  icon: 'music'
  color: 'blue'

inputs:

  bach-arguments:
    required: true
    default: 'build'
    description: 'The arguments to be passed to Bach.
                  Defaults to `build`.'

  bach-version:
    required: true
    default: '17-ea'
    description: 'The version of Bach to initialize.
                  Find available versions listed at https://github.com/sormuras/bach/releases.
                  Defaults to `17-ea`.'

  working-directory:
    required: true
    default: ${{ github.workspace }}
    description: 'The working directory to change into.
                  Defaults to the common GitHub workspace directory'

runs:
  using: 'composite'
  steps:
    - name: 'Print information'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Print input values"
        echo "inputs.bach-version=${{ inputs.bach-version }}"
        echo "inputs.bach-arguments=${{ inputs.bach-arguments }}"
        echo "inputs.working-directory=${{ inputs.working-directory }}"
        echo "::endgroup::"
        echo "::group::Print version information"
        jshell --version
        java --version
        echo "::endgroup::"
    - name: 'Initialize Bach'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Initialize Bach"
        if [[ ! -f .bach/bin/bach ]]
        then
          jshell https://bit.ly/bach-init
        fi
        if [[ ! -x .bach/bin/bach ]]
        then
          chmod u+x .bach/bin/bach
        fi
        .bach/bin/bach --version
        if [[ ! "$(.bach/bin/bach --version)" == "${{ inputs.bach-version }}" ]]
        then
          java .bach/bin/init.java ${{ inputs.bach-version }}
        fi
        .bach/bin/bach --version
        echo "::endgroup::"
    - name: 'Run Bach ${{ inputs.bach-version }}'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo ".bach/bin/bach ${{ inputs.bach-arguments }}"
        .bach/bin/bach ${{ inputs.bach-arguments }}
