
name: 'bach-build'

description: 'Build a modular Java project with Bach'

branding:
  icon: 'music'  
  color: 'blue'

inputs:
  bach-action:
    description: 'Bach action to execute, defaults to build'
    required: true
    default: 'build'
  bach-version:
    description: 'Version of Bach to use, defaults to 16'
    required: true
    default: '16'
  project-name:
    description: 'Name of the project'
    required: false
  project-version:
    description: 'Version of the project'
    required: false
  project-main-release:
    description: 'Compile main modules for the specified Java SE release'
    required: false
  project-main-jarslug:
    description: 'String suffix used within the JAR file name, defaults to the project-version'
    required: false
    default: '!'
  working-directory:
    description: 'Working directory, defaults to github.workspace'
    required: true
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: 'Print information'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::List input values given to this action"
        echo "pwd=$(pwd)"
        echo "inputs.bach-action=${{ inputs.bach-action }}"
        echo "inputs.bach-version=${{ inputs.bach-version }}"
        echo "inputs.project-name=${{ inputs.project-name }}"
        echo "inputs.project-version=${{ inputs.project-version }}"
        echo "inputs.project-main-release=${{ inputs.project-main-release }}"
        echo "inputs.project-main-jarslug=${{ inputs.project-main-jarslug }}"
        echo "inputs.working-directory=${{ inputs.working-directory }}"
        echo "::endgroup::"
        jshell --version
        java --version
    - name: 'Run Bach'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        name=$([ "${{ inputs.project-name }}" = "" ]             && echo "" || echo " -R-Dbach.project.name=${{ inputs.project-name }}")
        version=$([ "${{ inputs.project-version }}" = "" ]       && echo "" || echo " -R-Dbach.project.version=${{ inputs.project-version }}")
        release=$([ "${{ inputs.project-main-release }}" = "" ]  && echo "" || echo " -R-Dbach.project.main.release=${{ inputs.project-main-release }}")
        jarslug=$([ "${{ inputs.project-main-jarslug }}" = "!" ] && echo "" || echo " -R-Dbach.project.main.jarslug=${{ inputs.project-main-jarslug }}")
        options=${name}${version}${release}${jarslug}
        loadurl="-R-Dversion=${{ inputs.bach-version }} https://bit.ly/bach-main-${{ inputs.bach-action }}"
        echo "::group::Arguments passed to JShell"
        echo "options=${options}"
        echo "loadurl=${loadurl}"
        echo "::endgroup::"
        jshell ${options} ${loadurl}
